using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace Inventorer
{
    public partial class EditPart : ItemDetailForm
    {
        public EditPart()
        {
            InitializeComponent();
            EditPageLabel.Text = "Add Part";
            IDInput.Text = "autogenerated";
            IDInput.Enabled = false;
            isNew = true;
            SourceLabel.Text = "Machine ID";
            LoadForm();
        }

        public EditPart(Part part)
        {
            InitializeComponent();
            EditPageLabel.Text = "Modify Part";
            this.part = part;
            isNew = false;
            LoadPart(part);
        }
        public void LoadPart(Part part)
        {
            IDInput.Text = part.PartID.ToString();
            IDInput.Enabled = false;
            NameInput.Text = part.Name;
            CountInput.Text = part.Quantity.ToString();
            PriceInput.Text = part.Price.ToString();
            MinCountInput.Text = part.Min.ToString();
            MaxCountInput.Text = part.Max.ToString();
            if (part is Inhouse)
            {
                InHouseRadio.Select();
                SourceLabel.Text = "Machine ID";
                SourceIDInput.Text = part.GetMachineID().ToString();
            }
            else
            {
                OutsourcedRadio.Select();
                SourceLabel.Text = "Company Name";
                SourceIDInput.Text = part.GetCompanyName().ToString();
            }
            LoadForm();
        }
        public override void LoadForm()
        {
            base.LoadForm();
            SourceIDInput.CausesValidation = true;
            SourceIDInput.Validating += new System.ComponentModel.CancelEventHandler(SourceIDInput_Validating);
        }
        private void SourceIDInput_Validating(object sender, CancelEventArgs e)
        {
            if (!InHouseRadio.Checked)
            {
                e.Cancel = SourceIDInput.Text.Length == 0;
            }
            else
            {
                e.Cancel = !int.TryParse(SourceIDInput.Text, out _);
            }
            if (e.Cancel)
            {
                SourceIDInput.BackColor = Color.Pink;
            }
        }
        public override void SaveItem()
        {
            try
            {
                if (isNew)
                {
                    if (InHouseRadio.Checked)
                    {
                        Inventory.AddPart(new Inhouse(
                                NameInput.Text,
                                Convert.ToDouble(PriceInput.Text),
                                Convert.ToInt32(CountInput.Text),
                                Convert.ToInt32(MinCountInput.Text),
                                Convert.ToInt32(MaxCountInput.Text),
                                Convert.ToInt32(SourceIDInput.Text)
                        ));
                    }
                    else
                    {
                        Inventory.AddPart(new Outsourced(
                            NameInput.Text,
                            Convert.ToDouble(PriceInput.Text),
                            Convert.ToInt32(CountInput.Text),
                            Convert.ToInt32(MinCountInput.Text),
                            Convert.ToInt32(MaxCountInput.Text),
                            SourceIDInput.Text
                        ));
                    }
                }
                else
                {
                    Part updatedPart;
                    if (InHouseRadio.Checked)
                    {
                        updatedPart = new Inhouse(
                                Convert.ToInt32(IDInput.Text),
                                NameInput.Text,
                                Convert.ToDouble(PriceInput.Text),
                                Convert.ToInt32(CountInput.Text),
                                Convert.ToInt32(MinCountInput.Text),
                                Convert.ToInt32(MaxCountInput.Text),
                                Convert.ToInt32(SourceIDInput.Text)
                                );
                    }
                    else
                    {
                        updatedPart = new Outsourced(
                                Convert.ToInt32(IDInput.Text),
                                NameInput.Text,
                                Convert.ToDouble(PriceInput.Text),
                                Convert.ToInt32(CountInput.Text),
                                Convert.ToInt32(MinCountInput.Text),
                                Convert.ToInt32(MaxCountInput.Text),
                                SourceIDInput.Text
                                );
                    }

                    Inventory.ModPart(Convert.ToInt32(IDInput.Text), updatedPart);
                }
                this.Hide();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Unable to save: {ex.Message}", "Save Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
            
        }

        private void EditPart_Load(object sender, EventArgs e) {}

        private void InHouseRadio_CheckedChanged(object sender, EventArgs e)
        {

        }
    }
}
