using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Windows.Forms;

namespace Inventorer
{
    public partial class EditProduct : ItemDetailForm
    {
        public BindingSource partsBindingSource = new BindingSource();
        public BindingList<Part> partsBindingList = new BindingList<Part>(Inventory.AllParts);
        public BindingSource associatedPartsBindingSource = new BindingSource();
        public BindingList<Part> associatedPartsBindingList = new BindingList<Part>();
        //public Product product;

        public EditProduct(Product product)
        {
            InitializeComponent();
            isNew = false;
            IDInput.Enabled = false;
            EditPageLabel.Text = "Modify Product";
            LoadProduct(product);
            this.product = product;
            LoadForm();
        }

        public EditProduct()
        {
            InitializeComponent();
            IDInput.Text = "autogenerated";
            IDInput.Enabled = false;
            isNew = true;
            EditPageLabel.Text = "New Product";
            LoadForm();
        }

        public override void LoadForm()
        {
            base.LoadForm();
            SourceIDInput.Hide();
            SourceLabel.Hide();
            InHouseRadio.Hide();
            OutsourcedRadio.Hide();
            allPartsListDataGrid.DataSource = partsBindingList;
            allPartsListDataGrid.Columns["Price"].DefaultCellStyle.Format = "c";
            allPartsListDataGrid.Columns["Price"].HeaderText = "Price / Cost Per Unit";
            allPartsListDataGrid.Columns["PartID"].HeaderText = "Part ID";
            allPartsListDataGrid.Columns["CompanyName"].Visible = false;
            allPartsListDataGrid.Columns["MachineID"].Visible = false;
            allPartsListDataGrid.Columns["Min"].Visible = false;
            allPartsListDataGrid.Columns["Max"].Visible = false;

            associatedPartsDataGrid.DataSource = associatedPartsBindingList;
            associatedPartsDataGrid.Columns["Price"].DefaultCellStyle.Format = "c";
            associatedPartsDataGrid.Columns["Price"].HeaderText = "Price / Cost Per Unit";
            associatedPartsDataGrid.Columns["PartID"].HeaderText = "Part ID";
            associatedPartsDataGrid.Columns["CompanyName"].Visible = false;
            associatedPartsDataGrid.Columns["MachineID"].Visible = false;
            associatedPartsDataGrid.Columns["Min"].Visible = false;
            associatedPartsDataGrid.Columns["Max"].Visible = false;

            
        }

        private void LoadProduct(Product product)
        {
            IDInput.Text = product.GetProductID().ToString();
            IDInput.Enabled = false;
            NameInput.Text = product.GetName();
            CountInput.Text = product.GetQuantity().ToString();
            PriceInput.Text = product.GetPrice().ToString();
            MinCountInput.Text = product.GetMin().ToString();
            MaxCountInput.Text = product.GetMax().ToString();
            foreach (Part part in product.GetAssociatedParts()) 
            {
                associatedPartsBindingList.Add(part);
            }
        }
        
        private void PartSearchInput_Enter(object sender, EventArgs e)
        {
            partSearchInput.Text = (partSearchInput.Text == "Search by Part ID") ? "" : partSearchInput.Text;
        }

        private void PartSearchInput_Leave(object sender, EventArgs e)
        {
            partSearchInput.Text = (partSearchInput.Text == "") ? "Search by Part ID" : partSearchInput.Text;
        }

        private void PartSearchButton_Click(object sender, EventArgs e)
        {
            bool found = false;
            if (!int.TryParse(partSearchInput.Text, out int searchID))
            {
                MessageBox.Show("Must be a number", "Validation Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            foreach (DataGridViewRow row in allPartsListDataGrid.Rows)
            {
                Part part = (Part)row.DataBoundItem;
                if (part.PartID == searchID)
                {
                    row.Selected = true;
                    found = true;
                    break;
                }
            }
            if (!found) { MessageBox.Show("Part ID not found", "Search Error", MessageBoxButtons.OK, MessageBoxIcon.Warning); }
        }

        private void AddPartButton_Click(object sender, EventArgs e)
        {
            try
            {
                DataGridViewRow selectedRow = allPartsListDataGrid.SelectedRows[0];
                var idVal = selectedRow.Cells["PartID"].Value;

                int partID = Convert.ToInt32(selectedRow.Cells["PartID"].Value);
                Part part = Inventory.FindPart(partID);

                associatedPartsBindingList.Add(part);
            }
            catch (NullReferenceException)
            {
                MessageBox.Show("partID is null", "Search Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }
            catch (ArgumentOutOfRangeException)
            {
                MessageBox.Show("partID does not exist", "Search Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
            RefreshButtonStates();
        }

        
        private void DelPartButton_Click(object sender, EventArgs e)
        {
            try
            {
                DataGridViewRow selectedRow = associatedPartsDataGrid.SelectedRows[0];
                int partID = Convert.ToInt32(selectedRow.Cells["PartID"].Value);
                Part partToDelete = Inventory.FindPart(partID);
                associatedPartsBindingList.Remove(partToDelete);
                RefreshButtonStates();
            }
            catch (Exception)
            {
                MessageBox.Show("partID does not exist", "Search Error", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }

        }
        

        private void RefreshButtonStates()
        {
            delPartButton.Enabled = associatedPartsBindingList.Count().Equals(0) ? false : true;
        }

        public override void saveButton_Click(object sender, EventArgs e)
        {
            base.saveButton_Click(sender, e);
        }
        public override void SaveItem()
        {
            try
            {
                ArrayList associatedPartsToSave = new ArrayList();
                foreach (Part part in associatedPartsBindingList)
                {
                    associatedPartsToSave.Add(part);
                }

                if (isNew)
                {
                    Inventory.AddProduct(new Product(
                        NameInput.Text,
                        Convert.ToDouble(PriceInput.Text),
                        Convert.ToInt32(CountInput.Text),
                        Convert.ToInt32(MinCountInput.Text),
                        Convert.ToInt32(MaxCountInput.Text),
                        associatedPartsToSave
                        ));
                }
                else
                {
                    Product updatedProduct;
                    updatedProduct = new Product(
                            Convert.ToInt32(IDInput.Text),
                            NameInput.Text,
                            Convert.ToDouble(PriceInput.Text),
                            Convert.ToInt32(CountInput.Text),
                            Convert.ToInt32(MinCountInput.Text),
                            Convert.ToInt32(MaxCountInput.Text),
                            associatedPartsToSave
                            );
                    Inventory.ModProduct(Convert.ToInt32(IDInput.Text), updatedProduct);
                }
                this.Hide();
            }
            catch (Exception ex)
            {
                MessageBox.Show($"Unable to save: {ex.Message}", "Save Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
                return;
            }
           
        }
    }
}
